import Head from 'next/head';
import Layout from 'components/Layout/Layout';
import Alert from 'components/Alert/Alert';

const Demo = () => {
  return (
    <>
      <Head>
        <title>hello</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main>
          <Alert type='error'>
            <h2>hello222</h2>
          </Alert>
          <img src='/next.svg' alt='' />
        </main>
      </Layout>
    </>
  );
};

export default Demo;
